services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

  backend:
    build: "./Backend"
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frondend:
    build: "./frontend"
    ports:
      - "3000:3000"
